services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: backend_chmnu_schedule:latest
    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: "sh /entrypoint.sh"
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - static:/app/static/
      - ..:/app/
    restart: unless-stopped

  proxy:
    build: ../nginx
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - main-app
    volumes:
      - static:/static/
    restart: always

volumes:
  static:
