version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: chmnu-db
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgres/data
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}

volumes:
  postgres_data: