services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: backend_chmnu_schedule:latest
    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ../.env
    volumes:
      - ..:/app/
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: chmnu-db
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
