# Generated by Django 5.1.3 on 2026-05-18 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(choices=[('admin', 'Admin'), ('headman', 'Headman'), ('client_manager', 'Client Manager'), ('faculty_manager', 'Faculty Manager'), ('teacher_manager', 'Teacher Manager'), ('subject_manager', 'Subject Manager'), ('room_manager', 'Room Manager'), ('group_manager', 'Group Manager'), ('schedule_manager', 'Schedule Manager'), ('default', 'Default')], max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('first_name', models.CharField(max_length=100, verbose_name="Client's First Name")),
                ('last_name', models.CharField(max_length=100, verbose_name="Client's Last name")),
                ('middle_name', models.CharField(max_length=100, verbose_name="Client's Middle Name")),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name="Client's email for auth")),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('is_email_confirmed', models.BooleanField(default=False, verbose_name='Has the client confirmed their email and set a password')),
                ('roles', models.ManyToManyField(related_name='clients', to='clients.role', verbose_name="Client's Roles")),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientEmailConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='One-time confirmation token')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration time')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='When the token was used (consumed)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmation_tokens', to='clients.client', verbose_name='Client this token belongs to')),
            ],
            options={
                'verbose_name': 'Client Email Confirmation Token',
                'verbose_name_plural': 'Client Email Confirmation Tokens',
                'indexes': [models.Index(fields=['token'], name='clients_cli_token_fd3362_idx')],
            },
        ),
        migrations.CreateModel(
            name='IssuedJwtToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('jti', models.UUIDField(editable=False, unique=True, verbose_name='JWT Token unique ID')),
                ('device_id', models.CharField(max_length=36, verbose_name='JWT Token device ID')),
                ('expiration_time', models.IntegerField(verbose_name='UNIX timestamp expiration time of the token')),
                ('revoked', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_jwt_tokens', to='clients.client', verbose_name='Tokens subject')),
            ],
            options={
                'verbose_name': 'JWT Token',
                'verbose_name_plural': 'JWT Tokens',
                'indexes': [models.Index(fields=['expiration_time'], name='clients_iss_expirat_ccd557_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'),
        ),
    ]
