# Generated by Django 5.0.4 on 2024-06-28 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('first_name', models.CharField(max_length=100, verbose_name="Client's First Name")),
                ('last_name', models.CharField(max_length=100, verbose_name="Client's Last name")),
                ('middle_name', models.CharField(max_length=100, verbose_name="Client's Middle Name")),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('headman', 'Headman'), ('default', 'Default')], default='default', verbose_name="Client's role")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name="Client's email for auth")),
                ('password', models.CharField(max_length=250)),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name="Client's Token")),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
