FROM nginx:1.27.2-alpine

RUN apk add --no-cache curl

COPY ./nginx.prod.conf.template /etc/nginx/templates/default.conf.template
COPY ./well-known/assetlinks.json /var/www/well-known/assetlinks.json

RUN rm -f /etc/nginx/conf.d/default.conf
