# Generated by Django 5.1.3 on 2026-05-18 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Per-device external identifier')),
                ('player_id', models.CharField(max_length=100, verbose_name='OneSignal player ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is subscription active')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last time the device was seen')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='schedule.group', verbose_name='Subscribed group')),
            ],
            options={
                'verbose_name': 'Group Push Subscription',
                'verbose_name_plural': 'Group Push Subscriptions',
                'constraints': [models.UniqueConstraint(fields=('player_id', 'group'), name='unique_group_push_player')],
            },
        ),
        migrations.CreateModel(
            name='TeacherPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Per-device external identifier')),
                ('player_id', models.CharField(max_length=100, verbose_name='OneSignal player ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is subscription active')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last time the device was seen')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='schedule.teacher', verbose_name='Subscribed teacher')),
            ],
            options={
                'verbose_name': 'Teacher Push Subscription',
                'verbose_name_plural': 'Teacher Push Subscriptions',
                'constraints': [models.UniqueConstraint(fields=('player_id', 'teacher'), name='unique_teacher_push_player')],
            },
        ),
    ]
