from .main import *  # noqa


ALLOWED_HOSTS = env('ALLOWED_HOSTS')  # noqa
DEBUG = False
ELASTIC_APM['DEBUG'] = False  # noqa
CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS')  # noqa
CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')  # noqa

DJANGO_SUPERUSER_PASSWORD = env('DJANGO_SUPERUSER_PASSWORD') # noqa
DJANGO_SUPERUSER_USERNAME = env('DJANGO_SUPERUSER_USERNAME') # noqa
DJANGO_SUPERUSER_EMAIL = env('DJANGO_SUPERUSER_EMAIL') # noqa
